### ISSUE TITLE
SaveSynonym should use `forwardToReplicas` instead of `forwardToSlaves`

### ISSUE THREAD

**Issue by pixelastic** [algolia/algoliasearch-client-csharp#174]
Following our internal renaming initiative, the `SaveSynonym` method should have a few minor adjustements. The REST API now accepts `forwardToReplicas` in addition to `forwardToSlaves` when adding synonyms. All the documentation is being updated so it mentions `forwardToReplicas`.

The C# client should send `forwardToReplicas` instead of `forwardToSlaves`. Internal variables could also be renamed.

**Comment by CBaptiste** [comment]
done
