### ISSUE TITLE
PartialUpdateObjects

### ISSUE THREAD

**Issue by BooMWax** [algolia/algoliasearch-client-csharp#18]
Not so far to method 'PartialUpdateObject' was added argument 'createIfNotExists'. That allows user not to add some partial information to algolia when for some reason full object was not stored to index.

For me most likely case to partially update batch of objects. That's why it would be greate to add the same parameter to 'PartialUpdateObjects' method:
PartialUpdateObjects(batch, bool createIfNotExists = true).
And, of course, to it async clone.

**Comment by Nagriar** [comment]
Thanks @BooMWax  to help us to improve our client.

**Comment by BooMWax** [comment]
Thanks @Nagriar !
