### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by BooMWax** [algolia/algoliasearch-client-csharp#19]
Please add functionality that will provide user with index 'Logs'.
I suppose it should be 'index' method with signature like:
index.GetLogs(pageNumber = 0, logsPerPage = 1000) - exactly like 'Browse' method.

**Comment by Nagriar** [comment]
Hi @BooMWax,

For performance reason and to save SSD space on the servers, we only store the last 1000 calls on the machine, that's why the method doesn't work like the browse method.

Best regards,

**Comment by BooMWax** [comment]
@Nagriar,
as far as I understand from this page (https://www.algolia.com/doc/rest#get-last-logs)
I can pass 'offset' and 'length' and retrieve actually every range for logs (let's say logs from 200 to 1200). Am I wrong?
