### ISSUE TITLE
Logs by date

### ISSUE THREAD

**Issue by BooMWax** [algolia/algoliasearch-client-csharp#20]
It will be very usefull to retrieve index logs not by pages but by date ranges, let's say
since DateTime1 to DateTime2
Please add such method to index.

**Comment by Nagriar** [comment]
@BooMWax ,

As explained in the #19, the only keep 1000 logs for the whole appID, the filter per index won't be relevant because if you have an index with a huge number of query the other won't have logs.

Best regards,

**Comment by BooMWax** [comment]
@Nagriar,

yeah, after discussion in #19 I get it.
