### ISSUE TITLE
.NET Core compatibility

### ISSUE THREAD

**Issue by olance** [algolia/algoliasearch-client-csharp#259]
Would it be possible to target the .NET Core platform as well?

**Comment by CBaptiste** [comment]
Hello, sorry for the delay !

So I looked into and there s definitely a compatibility issue here since we are using dlls methods that are not portable to .NET Core or even .Net Framework (we target .Net Portable)
I ll try to evaluate the impact of such switch and let you know if that is something we ll do in the following weeks

**Comment by eat-sleep-code** [comment]
Any update on this?

**Comment by eat-sleep-code** [comment]
@olance I have _just_ discovered that installing the **Microsoft.NETCore.Portable.Compatibility** package will allow you to compile this for .NET Core..

@CBaptiste  Perhaps you can alter the Nuget package to add this dependency (or at least update the instructions to point this out).

**Comment by CBaptiste** [comment]
Very useful insight, I ll check it out tomorow 👍 

Thank you for the input

**Comment by olance** [comment]
@eat-sleep-code Thanks a lot for the info :)

**Comment by taho101** [comment]
Hello, when can we expect support for .NET Core to be released?
I am working on a project that uses Core and I can not use the Algolia client :)

**Comment by CBaptiste** [comment]
Hello @taho101,

Right now we cannot provide any ETA yet but there is a workaround: Microsoft.NETCore.Portable.Compatibility. 
If you import this package, you should be able to use our client, we tested it and it works fine on a .NET Core platform !
Let me know how it goes :)

**Comment by CBaptiste** [comment]
Finally ready \o/
We ll release the .Core support next week and we will drop support to .NET 4.0 and 4.5 at the same time - outdated

**Comment by andymac4182** [comment]
@CBaptiste Curious why you chose to target `netcoreapp` as well as `netstandard`?
