### ISSUE TITLE
Query.GetQueryString is inconsistent with Query.SetQueryString 

### ISSUE THREAD

**Issue by ttsushko** [algolia/algoliasearch-client-csharp#272]
Query.GetQueryString returns query string with all query parameters, while Query.SetQueryString only sets parameter named query, this is not consistent and not obvious.
I found similar issue with Andoid client: https://github.com/algolia/algoliasearch-client-android/issues/28, and seems this logic was changed.

Are there any plans for changing it in next major release?

**Comment by CBaptiste** [comment]
Hello @ttsushko ! Sorry for the delay,

No nothing is planned for now, but I ll try do it soon, it s a good point.
I ll update the issue !

Thx for reporting it :)

**Comment by Ant-hem** [comment]
Resolved with version 6.0- 0fc38a6
