### ISSUE TITLE
Randomize the array of hosts

### ISSUE THREAD

**Issue by kokliKo** [algolia/algoliasearch-client-csharp#28]
The code acting "as a load-balancer" to randomize the Algolia hosts isn't implemented yet: https://github.com/algolia/algoliasearch-client-csharp/blob/19f3fc430b7dec6d0ec7a522c21e7e33e9c20863/Algolia.Search/AlgoliaClient.cs#L100

**Comment by CBaptiste** [comment]
it is done - pull request merged
