### ISSUE TITLE
Cannot install package on VS2017

### ISSUE THREAD

**Issue by gym-in** [algolia/algoliasearch-client-csharp#340]
`Install-Package : Could not install package 'Algolia.Search 4.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0',
 but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author
.`

I tried every supported framework in the README.md file, but still no luck in installing the package.

**Comment by spinach** [comment]
Hello!

Thanks for letting us know. We forgot to update the Supported Platforms on the Readme, sorry about that and thanks for pointing that out.

The support for [.NET 4.0 has been deprecated](https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/), so we don't support it anymore. Try to use v4.6 for example and it should work.

Let us know if you face any more issue.
