### ISSUE TITLE
Interface for AlgoliaClient and Index?

### ISSUE THREAD

**Issue by svickers** [algolia/algoliasearch-client-csharp#493]
Would be nice if these classes implemented an interface so we could mock them in unit tests.  I'm happy to define one based on the current implementation and send a PR if it has any hope of getting approved.

**Comment by spinach** [comment]
Hi @svickers,

Thank you for this feedback. Indeed you are definitely right, it would be a better practice to have classes implement an interface for the ability to mock (and more). 

We are definitely open for PRs and will be glad to review and approve it if no issues arise. Please don't hesitate to send one, I definitely encourage you to do this.

**Comment by Ant-hem** [comment]
Resolved with version 6.0- 0fc38a6
