### ISSUE TITLE
AddExtraQueryParameters should be able to take an array of values

### ISSUE THREAD

**Issue by spinach** [algolia/algoliasearch-client-csharp#501]
### Description

- in the API docs, there is a sample call to RequestOptions().AddExtraQueryParameters() with an array of strings as second parameter (https://www.algolia.com/doc/api-reference/api-parameters/optionalFilters/)
- in the C# client's code, the second parameter of AddExtraQueryParameters() must be string (https://github.com/algolia/algoliasearch-client-csharp/blob/836fedb90bbabbbc959b8d14ab56da41ea729826/Algolia.Search/Models/RequestOptions.cs#L29)
- in the C# client's tests, just a single test is provided, with a single string value (https://github.com/algolia/algoliasearch-client-csharp/blob/4b5155d0fb81acb19ec9c4cdf7b12da97f1bcc03/Algolia.Search.Test/AlgoliaClientTest.cs#L976)

**Comment by Ant-hem** [comment]
Resolved with version 6.0- 0fc38a6
