### ISSUE TITLE
No sources or changelog for Algolia.Search 5.0.0

### ISSUE THREAD

**Issue by sjmulder** [algolia/algoliasearch-client-csharp#503]
Steps:

1. Open the NuGet package manager
2. Search for Algolia.Search. Observe that version 5.0.0 is available
3. Inspect this repository

Expected results:
 - Updated sources are there
 - A 5.0 release exists
 - The ChangeLog is updated up to 5.0

Actual results: none of the above.

(Perhaps an oversight?)

**Comment by julienbourdeau** [comment]
Hi @sjmulder Thanks for reporting this issue. I believe something went wrong somewhere, there shouldn't be any 5.0.0 version. Lastest one is still 4 something. I'll have a deeper look.

**Comment by sjmulder** [comment]
Cheers, we'll stick with 4.x then.

**Comment by spinach** [comment]
Hey @sjmulder,

My bad on this, I forgot to push the ChangeLog. We did end up releasing a major version 5.0.0. You can check the new [ChangeLog](https://github.com/algolia/algoliasearch-client-csharp/blob/master/ChangeLog#L4). Thanks a lot for reporting this and helping us improve our repo 🙂

**Comment by sjmulder** [comment]
Great, thanks!
