### ISSUE TITLE
DeleteObject is not deleting the entry after migrating to 6.0.0

### ISSUE THREAD

**Issue by KamleshArya** [algolia/algoliasearch-client-csharp#535]
- Algolia Client Version: 6.0.0
- Language Version: C# 6.0

### Description
Hi,
We are using the following code to delete an object from Algolia
  index.DeleteObject(ObjectID); 

However, it's not deleting the entry after upgrading to version 6.0.0

**Comment by Ant-hem** [comment]
Hey!

Thanks for your contribution, it's a good catch!

There is an error in the URI of the `DeleteObject` method. I'll submit a PR today and deploy a fix with `6.0.1` in a few days. I'll keep you updated when the fix is deployed.

**Comment by Ant-hem** [comment]
Solved with [6.0.1](https://www.nuget.org/packages/Algolia.Search/6.0.1)

**Comment by KamleshArya** [comment]
Thanks :)
