### ISSUE TITLE
Deserialization change in newest v.6 client

### ISSUE THREAD

**Issue by kevinp** [algolia/algoliasearch-client-csharp#541]
We've just run our integration process with the new v6 client.

Our index attributes are now all suddenly camelCase which has broken our configuration.

PromotedName  is now promotedName

Can you please investigate?

![image](https://user-images.githubusercontent.com/438896/52639033-302a0180-2e88-11e9-92e8-cedd28ea61ed.png)

**Comment by Ant-hem** [comment]
Hi!

The V6 is different than before for the serialization. 

As you can see [there](https://github.com/algolia/algoliasearch-client-csharp/blob/1dbe4c57f3eb3690e44b3efdf32a58322cdfcb1d/src/Algolia.Search/Serializer/JsonConfig.cs#L42) the default strategy for the serializer is camelCasing. This allow us to respect PascalCasing convention for C# classes and to respect Json Convention as well (all classes are then serialized to camelCase). 

If you want you classes to be serialized in PascalCase you can use the following attributes from JSON.NET

At the class level:
```csharp
[JsonObject(NamingStrategyType = typeof(PascalCaseNamingStrategy))]
public class Foo
{
}
```

Or at the property level:
```csharp
[JsonProperty(PropertyName = "MyProperty")]
public string MyProperty {get; set;}
```

**Comment by kevinp** [comment]
Got it.  Thanks @Ant-hem , I somehow missed that in the upgrade docs.

**Comment by kevinp** [comment]
Just a note, that ultimately this is what was required.  @Ant-hem , it seems odd that we're now required to explicitly declare a default strategy.  Either way, it's now working for us.   Thanks.

```
    [JsonObject(NamingStrategyType = typeof(DefaultNamingStrategy))]
```

**Comment by Ant-hem** [comment]
Yes, I am sorry about that. 

It's because we are now respecting the [standard](https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format) name format (camelCase) for JSON which is also implemented by the engine. That's why we implemented as default, the camelCase naming strategy for serializing C# classes (which can stay PascalCased).
