### ISSUE TITLE
CallType.Read on sendEvents

### ISSUE THREAD

**Issue by q-litzler** [algolia/algoliasearch-client-csharp#546]
https://github.com/algolia/algoliasearch-client-csharp/blob/660d709dafd6c3d338eae3a2b771c7b27faaa08b/src/Algolia.Search/Clients/InsightsClient.cs#L133

Shouldn't this be CallType.Write ?

**Comment by Ant-hem** [comment]
Hello! 

Thanks for catching it.

I'll submit a PR to fix it!
