### ISSUE TITLE
Facet Stats not being returned

### ISSUE THREAD

**Issue by barnesoir** [algolia/algoliasearch-client-csharp#551]
- Algolia Client Version: 6.1.0
- Language Version: C# .net core 2.1/2.2

### Description
Upgraded to 6.1.0 to fix #547.
I've now noticed facet stats aren't being returned as well

### Steps To Reproduce
5.x.x code that returns stats:
`var facetStatQuery = new Query().SetFilters(filter).SetFacets(facets);
var facetStatJObject = _index.Search(facetStatQuery);`

V6 code that doesn't return stats:
`_index.Search<object>(new Query()
                {
                    Filters = filter,
                    Facets = facets
                });`

**Comment by Ant-hem** [comment]
Hello 👋 

Thank for your contribution.

You're right there is a typo in the `[JsonPropertyAttribute("facet_stats")]` it should be `[JsonPropertyAttribute("facets_stats")]` (missing an **s**)

I'll submit a PR to fix this and ship a patch by the end of the week.

**Comment by Ant-hem** [comment]
@barnesoir Fixed with [6.1.1](https://www.nuget.org/packages/Algolia.Search/6.1.1)
