### ISSUE TITLE
Response Code 400: The 'objectID' attribute is required to use action=updateObject

### ISSUE THREAD

**Issue by kevinp** [algolia/algoliasearch-client-csharp#558]
- Algolia Client Version: 6.1.1
- Language Version: Csharp

When I run a series of updates on our index, I'm getting the intermittent error:

```
{
  "message": "The 'objectID' attribute is required to use action=updateObject near line:1 column:20640",
  "status": 400
}
```

However when I inspect the request in the log in the dashboard, the objectID attribute is there.  Most of my updates succeed.  I can't figure out why these requests are failing.

Any thoughts?

```
{
  "requests": [
    {
      "action": "updateObject",
      "body": {
        "objectID": "Locations/18912",
        "LocationId": "Locations/18912",
        "CatalogId": "Catalogs/13718",
        "PropertyId": "Properties/18912",
        "Parents": [
          {
            "locationId": "Locations/10186",
            "promotedName": "Umbria",
            "propertyCount": 161
          },
          {
            "locationId": "Locations/10187",
            "promotedName": "Perugia",
            "propertyCount": 104
          },
          {
            "locationId": "Locations/10188",
            "promotedName": "Lake Trasimeno",
            "propertyCount": 41
          },
          {
            "locationId": "Locations/10270",
            "promotedName": "Tuoro sul Trasimeno",
            "propertyCount": 15
          },
          {
            "locationId": "Locations/4945",
            "promotedName": "Italy",
            "propertyCount": 2441
          }
        ],
        "BedroomsCount": 2,
        "SingleBedroomsCount":
```

**Comment by Ant-hem** [comment]
Hi!

Do you have a log of the payload you are sending to the API that we could inspect to see if an `objectID` is missing? This error occurs most likely if you have an empty or null `objectID`. 

If you don't have a log, can you use our built-in logger by setting the environment variable `ALGOLIA_DEBUG=true`and by running your application in `debug` mode? It will produce a `log.txt` in your `debug` folder.

**Comment by kevinp** [comment]
Hi!

I added the environment variable and ran in debug but no log.txt.  What logging library does it use?  

![image](https://user-images.githubusercontent.com/438896/53909524-bdcfbb80-4006-11e9-9372-ee230b546901.png)

However, I can review the logs in the dashboard and very clearly see that the objectID is present on the requests that are failing.

![image](https://user-images.githubusercontent.com/438896/53909621-00919380-4007-11e9-87d2-931dba9d9fb7.png)

![image](https://user-images.githubusercontent.com/438896/53909801-4f3f2d80-4007-11e9-9234-7aaa10e683cd.png)

**Comment by Ant-hem** [comment]
I will investigate and try to reproduce the issue on my side with the sample you gave us.

We don't use any logging library, [it's a simple stream writer](https://github.com/algolia/algoliasearch-client-csharp/blob/master/src/Algolia.Search/Http/AlgoliaHttpRequester.cs) logging requests and responses.

**Comment by Ant-hem** [comment]
Hi,

Did you face the issue again? I tried to reproduce on my side with the dataset you gave me. I didn't get any error performing a series of 500 batch update of one element.

If you still face the issue, could you please write to [Algolia's support](https://www.algolia.com/support/#home) referencing this issue? It could be an issue on the engine side.

**Comment by kevinp** [comment]
Hey @Ant-hem , sorry somehow I must have forgot to hit submit on my close/comment last week.  You were right that once I inspected the complete dataset, not just the partial from the logs in the dashboard, there were some items that had blank objectID values.  Once I resolved that everything ran fine.

**Comment by Ant-hem** [comment]
Thanks for keeping us updated! I am closing the issue then.
