### ISSUE TITLE
Investigate why DnsTimeOutTest is not working as expected

### ISSUE THREAD

**Issue by Ant-hem** [algolia/algoliasearch-client-csharp#586]
The domain `algolia.biz` can't be requested from the client:

```csharp
System.Net.Http.HttpRequestException: Device not configured ---> System.Net.Sockets.SocketException: Device not configured
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
```

**Comment by spinach** [comment]
So this seems to have been marked as done on the parent issue, and I haven't seen this issue in the latest CI build runs. 
Will close as this is 1 year old.

Feel free to re-open if you feel this is a mistake!
