### ISSUE TITLE
SearchRule and SearchRuleAsync method contain bad naming

### ISSUE THREAD

**Issue by nunomaduro** [algolia/algoliasearch-client-csharp#595]
### Description

The following methods should be in plural: `SearchRule` => `SearchRules` and `SearchRuleAsync` => `SearchRulesAsync` to respect the API Client specs.

https://github.com/algolia/algoliasearch-client-csharp/blob/master/src/Algolia.Search/Clients/SearchIndex.cs:

```csharp
        SearchResponse<Rule> SearchRule(RuleQuery query = null, RequestOptions requestOptions = null);

        Task<SearchResponse<Rule>> SearchRuleAsync(RuleQuery query = null,
            RequestOptions requestOptions = null, CancellationToken ct = default);
```

*Goal*: Deprecate the current methods with bad naming, and proxy them to new methods with the good naming.

**Comment by morganleroi** [comment]
Closing the issue as this is now fixed in the 7.0 version of the client.
