### ISSUE TITLE
Add: IndexSettings -> userData

### ISSUE THREAD

**Issue by Ant-hem** [algolia/algoliasearch-client-csharp#601]
Add `UserData` property (object) in `IndexSettings`

**Comment by aseure** [comment]
Re-opening to make sure the CTS test is implemented in the same way across all our clients (see https://github.com/algolia/algoliasearch-client-specs-internal/pull/38).

**Comment by Ant-hem** [comment]
Already tested here 

https://github.com/algolia/algoliasearch-client-csharp/blob/78559ec0309b2cb163bc45b951c4334f85aa64c3/src/Algolia.Search.Test/EndToEnd/Index/SettingsTest.cs#L133
