### ISSUE TITLE
MaxFacetHits only returns 20 no matter what value is entered

### ISSUE THREAD

**Issue by elvogel** [algolia/algoliasearch-client-csharp#619]
- Algolia Client Version: 6.2.0
- Language Version: netcore 2.2

### Description

I have the following code in my ASP.NET Core app:
```csharp
var query = new Query("faq")
{
    RestrictSearchableAttributes = new List<string> {"slug"},
    Distinct = 0,
    MaxFacetHits = 50,
};
var items = index.Search<QuestionFile>(query);
log.LogInformation($"querying faq objects in index retrieved {items.Hits.Count} objects");
index.DeleteObjects(items.Hits.Select(s => s.slug));
```
I currently have well over 20 FAQ objects in my index, but no matter what value I assign the `MaxFacetHits` property, it always gives me 20.

**Comment by Ant-hem** [comment]
Answered on [discourse](https://discourse.algolia.com/t/maxfacethits-is-50-but-im-still-only-getting-20/8002) because the question is more about Algolia's feature and not the library. 

Will close this issue when question is answered.

**Comment by Ant-hem** [comment]
Closing this one. Don't hesitate to re-open it if you still have issues.
