### ISSUE TITLE
# tests(cts): update send_event/send_events tests adding timestamp

### ISSUE THREAD

**Issue by nunomaduro** [algolia/algoliasearch-client-csharp#626]
**Docs**: https://github.com/algolia/algoliasearch-client-specs/pull/31/files.

Here is an example on python: https://github.com/algolia/algoliasearch-client-python/pull/433/files.

**Goal**: make sure developers can set the event timestamp when sending events using send_event/send_events.

**Comment by Ant-hem** [comment]
Users can send timeStamp with the `InsightsRequest` class which is in the signature of every `sendEvents` method

https://github.com/algolia/algoliasearch-client-csharp/blob/41c49e55305552df281f6e6a6556c127fe65ab21/src/Algolia.Search/Clients/InsightsClient.cs#L105

and

https://github.com/algolia/algoliasearch-client-csharp/blob/41c49e55305552df281f6e6a6556c127fe65ab21/src/Algolia.Search/Models/Insights/InsightsRequest.cs#L67
