### ISSUE TITLE
Check automaticRadius type in search response is string

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-csharp#630]
A user of the Go client [reported](https://github.com/algolia/algoliasearch-client-go/issues/518)
on support that they had issue while the Go client was deserializing the
`automaticRadius` field of a geo search query.

The [Algolia documentation says](https://www.algolia.com/doc/api-reference/api-methods/search/?language=go#method-response-automaticradius)
the type of `automaticRadius` is a string but, as of today, the written type
annotation is marked to float.

Let's make sure that this field is correctly typed as a string (and not a
float), as it should.

For the record, to make `automaticRadius` in a search response, you need to
perform a search query with:

 - with a geo parameter such as `aroundLatLng`
 - without any `aroundRadius` search parameter
 - have records in your index that will match the geo query, so they need to
   have a `_geoloc` attribute

**Comment by Ant-hem** [comment]
All good there, it's a string 👍 
https://github.com/algolia/algoliasearch-client-csharp/blob/19acf1a377250a3b160acaae223757fe0fe0ed1a/src/Algolia.Search/Models/Search/SearchResponse.cs#L134
