### ISSUE TITLE
set settings.userData field in CTS test for index settings

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-csharp#631]
Specs: https://github.com/algolia/algoliasearch-client-specs/pull/38

**Comment by Ant-hem** [comment]
Already there:

https://github.com/algolia/algoliasearch-client-csharp/blob/3b6fdba091299c2fe08f1bbfcbc132d2717bfde6/src/Algolia.Search.Test/EndToEnd/Index/SettingsTest.cs#L133
