### ISSUE TITLE
feat: add .NET Core 3 support

### ISSUE THREAD

**Issue by Ant-hem** [algolia/algoliasearch-client-csharp#651]
The stable version of .NET Core 3 is coming end of the September.
 Let's make sure the library supports it.

**Comment by nunomaduro** [comment]
Wondering if we couldn't had a build that tests against the `nightly` version of `.NET Core` so we can be informed about potential issues.

Here is an example in PHP: https://github.com/algolia/algoliasearch-client-php/blob/602748161cecbf9d329379a9949d63e1dc683852/.travis.yml#L40

**Comment by Ant-hem** [comment]
Definitely, I'll be working on it in the coming days.
