### ISSUE TITLE
Analytics API

### ISSUE THREAD

**Issue by andymac4182** [algolia/algoliasearch-client-csharp#66]
Are you going to be extending this client to support the Analytics API?

**Comment by CBaptiste** [comment]
Hello @andymac4182 !
So no, we will not extend this client to support the analytics API, it would not make a lot of sense, it is not handled by the same set of machines and the logic is quite different. We encourage you to use the classic REST client for this (https://www.algolia.com/doc/rest#analytics-api)
Does that answer your question ?

**Comment by andymac4182** [comment]
No worries. I was just following the doco which says only use the REST api for new clients. :+1:
