### ISSUE TITLE
feat: adds restrictSources in Query

### ISSUE THREAD

**Issue by Ant-hem** [algolia/algoliasearch-client-csharp#669]
The following parameter is missing in `Query`

https://github.com/algolia/algoliasearch-client-java-2/blob/1712feab2cfb54f7b07e355673f84ba775e607a1/algoliasearch-core/src/main/java/com/algolia/search/models/indexing/SearchParameters.java#L509

**Comment by morganleroi** [comment]
Closing the issue as `RestrictSources` is now part of the `Query`, in the new 7.0 client we just released.
