### ISSUE TITLE
bug: SearchUserIDsRequest cluster parameter should be optional

### ISSUE THREAD

**Issue by nunomaduro** [algolia/algoliasearch-client-csharp#682]
The parameter `cluster` while using `searchUserIDs` should be optional:

 https://github.com/algolia/algoliasearch-client-csharp/blob/bb638b802b1322d00626c8fa78bc06fad49a5331/src/Algolia.Search/Models/Mcm/SearchUserIdsRequest.cs#L39

I am sorry, if I am missing something.

**Comment by Ant-hem** [comment]
Yes it's optional, if `cluster` is not set its value will be `null` and the serializer won't serialize it because it's null.
