### ISSUE TITLE
Set ObjectID not working for dynamic type and Dictionary type

### ISSUE THREAD

**Issue by vickyRathee** [algolia/algoliasearch-client-csharp#689]
I have an `ObjectID` field and it's value set in my `dynamic` type, but Aloglia still throw error saying 

``The type T must have an ObjectID property or a JsonPropertyAttribute with name='objectID'``

I tired to use ToDictionary and ToDynamic both method and also changed the the case to objectId. But the error can't go away.

**Code :** 

```
async Task Main()
{
	SearchClient client = new SearchClient("app id", "api key");
	SearchIndex index = client.InitIndex("index1");
	
	DataTable table = new DataTable();
	table.Columns.Add("ObjectID", typeof(string));
	table.Columns.Add("Value", typeof(string));

	table.Rows.Add("1", "Value 1");
	table.Rows.Add("2", "Value 2");
	table.Rows.Add("3", "Value 3");
	table.Rows.Add("4", "Value 4");

	var documents = table.ToDynamic();
	
	var algoliaResponse = await index.SaveObjectsAsync(documents, autoGenerateObjectId: false);
	algoliaResponse.Dump();
}

public static class DataTableExtensions
{
	public static List<Dictionary<string, object>> ToDictionary(this DataTable dt)
	{
		return dt.AsEnumerable().Select(
		row => dt.Columns.Cast<DataColumn>().ToDictionary(
			column => column.ColumnName,
			column => row[column]
		)).ToList();
	}

	public static List<dynamic> ToDynamic(this DataTable dt)
	{
		var dynamicDt = new List<dynamic>();
		foreach (DataRow row in dt.Rows)
		{
			dynamic dyn = new ExpandoObject();
			dynamicDt.Add(dyn);
			foreach (DataColumn column in dt.Columns)
			{
				var dic = (IDictionary<string, object>)dyn;
				dic[column.ColumnName] = row[column];
			}
		}
		return dynamicDt;
	}
}
```

**Error**

![image](https://user-images.githubusercontent.com/6106479/72867409-d622f480-3d04-11ea-902d-35d9bc513716.png)

**Comment by Ant-hem** [comment]
Hi,

The library is meant to be used with `POCO` or `JObject` to ensure our users they are sending correct data to the API. That's why the `saveObjects` method is checking if the data provided contains an `objectID` or not. However, you can still bypass this default behavior by calling directly the `Batch` method which is not performing extra validity check.

**Comment by vickyrathee** [comment]
@Ant-hem I see in code that you are not validating `JToken`, `JObject` etc. So if you can add the `dynmic` type as well to skip the validation will make it work I guess instead using Batch directly?

```
 if (itemType == typeof(JToken) || itemType == typeof(JObject) || itemType == typeof(JArray) ||
                itemType == typeof(JRaw))
            {
                return;
            }
```

https://github.com/algolia/algoliasearch-client-csharp/blob/a2240add0d429907b6ca325cf0d9c80302c40ddc/src/Algolia.Search/Utils/AlgoliaHelper.cs#L70

**Comment by Ant-hem** [comment]
It was made on purpose to help our users to migrate from v5 to v6. However, we could consider making this additional check optional for `dynamic` and `dictionary` as well in order to ease implementation for users not willing to use `POCOS`. What's your take on this @aseure?

**Comment by vickyrathee** [comment]
We are also migrating from v5 to v6. 
I will wait for your final decision before making any changes in our app. I guess there was no validation in v5 and our old code was working with dynamic, but failing now due to this validation helper.

**Comment by vickyrathee** [comment]
I fixed it on my end by converting the `DataTable` to `JArray` instead dynamic. Adding code here if it helps others

```
var documents = table.ToJson();
var algoliaResponse = await index.SaveObjectsAsync(documents, autoGenerateObjectId: false);
```

```
public static JArray ToJson(this DataTable source)
	{
		JArray result = new JArray();
		JObject row;
		foreach (DataRow dr in source.Rows)
		{
			row = new JObject();
			foreach (DataColumn col in source.Columns)
			{
				row.Add(col.ColumnName.Trim(), JToken.FromObject(dr[col]));
			}
			result.Add(row);
		}
		return result;
	}
```

**Comment by aseure** [comment]
I'm not as proficient in C# as you, so I'm not aware of any other simpler solutions than the manual conversion. This still has the drawback of not enforcing the presence of the `objectID` field, which is not desirable IMHO.

@Ant-hem Since `DataTable` is part of the standard library, could we imagine an overload for `saveObjects()` for this input type? Depending on the implementation complexity and actual usage of this class, this may be something that could improve the DX (I'd be happy to give the implementation a try if you think it's worthwhile @Ant-hem)
