### ISSUE TITLE
Ensure correct serialization of searchSynonyms' type query parameter

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-csharp#693]
When performing a `index.searchSynonyms()` call, a [`type` query
parameter](https://www.algolia.com/doc/rest-api/search/#method-param-type) can
be passed to restrict the type(s) of synonyms one wants to search for.

@maxiloc reported us that the Java implementation is accepting an array of
strings for this parameter. However, the engine only accepts a comma-separated
string for this. We then need to double check the implementation of the
serialization of this parameter and provide a fix if needed.

**Comment by Ant-hem** [comment]
Nothing to do here. Type is a `string`.
https://github.com/algolia/algoliasearch-client-csharp/blob/30332fab8eebffc07eb639ad1901334cca464d69/src/Algolia.Search/Models/Synonyms/SynonymQuery.cs#L48
