### ISSUE TITLE
6.8 drops support for .NET Framework?

### ISSUE THREAD

**Issue by ewahner** [algolia/algoliasearch-client-csharp#728]
- Algolia Client Version: 6.8.0
- Language Version:

### Description
6.7.0 seems like the last version to support .NET Framework?

### Steps To Reproduce
Search for Algolia.Search on NuGet

**Comment by Ant-hem** [comment]
Hi,

Algolia.Search `6.8.0` is compatible with [.NET Standard 1.3](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support) which is equivalent to .NET Framework 4.6 and higher (see link). However, that's true that between `6.7.0` and `6.8.0` we dropped the support of .NET Framework 4.5 (see [changelog](https://github.com/algolia/algoliasearch-client-csharp/blob/master/CHANGELOG.md#680-2020-08-17)).

Do you have any issue running the library with a specific version of the .NET Framework?

**Comment by Ant-hem** [comment]
Closing this, feel to re-open if you have any questions.
