### ISSUE TITLE
AverageClickPosition in Variant.cs should be a float

### ISSUE THREAD

**Issue by Ant-hem** [algolia/algoliasearch-client-csharp#736]
# Summary

The type of `averageClickPosition` field in variant response structure must be float.
It was revealed that it was set to int in the Go API Client, so we have to check its correctness among other clients.

https://github.com/algolia/algoliasearch-client-csharp/blob/master/src/Algolia.Search/Models/Analytics/Variant.cs#L48-L51

**Comment by Aallam** [comment]
By the way, there is a typo: `AverageClickPostion` -> `AverageClickPosition`
