### ISSUE TITLE
Need a way to add custom logging for the Http Request and Response

### ISSUE THREAD

**Issue by MingLu8** [algolia/algoliasearch-client-csharp#756]
It could be critical to log the http requests and responses from the http requests.
Current, there is hard code LogHelper.LogToFile(request.Body) in the AlgoliaHttpRequester.cs class's SendRequestAsync method and this classs is internal.  

There isn't an easy way to inject in a custom logger.

**Comment by Ant-hem** [comment]
Hello, 

> There isn't an easy way to inject in a custom logger.

That's true - it's something we could look at. cc @TomKlotzPro 

> Current, there is hard code LogHelper.LogToFile(request.Body) in the AlgoliaHttpRequester.cs class's SendRequestAsync

You can enable this logger by setting the `ALGOLIA_DEBUG` env variable if you need it for debugging purposes.
