### ISSUE TITLE
Ensure compatibility with .NET 6

### ISSUE THREAD

**Issue by mxa0079** [algolia/algoliasearch-client-csharp#813]
Algolia Client Version: 6.X
Language Version: .NET 6

Description

[.NET 5](https://devblogs.microsoft.com/dotnet/introducing-net-5/) is [out of support](https://dotnet.microsoft.com/en-us/download/dotnet). It is replaced by [.NET 6](https://devblogs.microsoft.com/dotnet/announcing-net-6/) which has had a official release for almost a month.

The current version should work with .NET 6, but it is still a good idea to move and adopt the latest framework and remove a dependency on an unsupported version.

**Comment by morganleroi** [comment]
Hello,

A new version of the client has been released on [Nuget](https://www.nuget.org/packages/Algolia.Search/7.0.0-alpha.0). You can use it with all dotnet core version as this client target the .net standard 2.0.

If you have time, we need customer feedback about this new version. It's still not GA so you may not want to use it in production.

There is no more deps on Newtonsoft, all Algolia APIs are now available (Insights, Recommend, Query Perso, ...) and all models and routes are synced.

To help you migrate, there is a [Migration guide](https://api-clients-automation.netlify.app/docs/clients/migration-guides/). 

Happy to help in your migration process !
