### ISSUE TITLE
PartialUpdateObject not working when using a JObject payload / the parser doesn't unwrap the objectId correctly

### ISSUE THREAD

**Issue by jsancho** [algolia/algoliasearch-client-csharp#815]
- Algolia Client Version: 6.12.1
- Language Version: C# .NET 6.0

### Description
Hi, 

I've noticed that the `PartialUpdateObject` was returning without error, but it was failing to actually update the record values on the index.

By debugging the project, I've noticed that the `objectId` value wasn't a string per se, but the JToken wrapper not fully deserialized.
![image](https://user-images.githubusercontent.com/1547884/179536979-01416f58-541a-4200-9a4b-519fe4940470.png)

Which ultimately lets the code run but doesn't generate the correct url, as the objectId is passed as json in the querystring to the Algolia API.

I've managed to add a fix on a local fork so that I could have a temporary fix to keep my solution running.

The diff below might better explain the issue and how to potentially solve it.
https://github.com/algolia/algoliasearch-client-csharp/compare/master...jsancho:algoliasearch-client-csharp:fix-partial-updates-objectid-parser

Could you please review and add a similar fix so that we can use partial updates with json payloads?

### Steps To Reproduce
```
// with payload being a 'JObject'
var index = _searchClient.InitIndex(indexName);
var result = await index.PartialUpdateObjectAsync(payload);
````

**Comment by sbellone** [comment]
Hi, thank you very much for the report and for the provided fix. I've added a couple of tests and made a PR, sorry it took us so long!

**Comment by jsancho** [comment]
hey @sbellone that's great news!
better late than never, really appreciate the fix 🥳

When should we expect a new version of the SDK to be published then?

**Comment by sbellone** [comment]
@jsancho finally released! Thanks again for your patience!

**Comment by jsancho** [comment]
> @jsancho finally released! Thanks again for your patience!

Fantastic, thanks a million! 🥳
