### ISSUE TITLE
BrowseAll Usage

### ISSUE THREAD

**Issue by ToineSeiter** [algolia/algoliasearch-client-csharp#83]
I'm trying to use the Browse method with a pager in a SEO purpose. 

I call the BrowseAll method with a query containing a facetfilter and a page number.
All works fine until I reach the last page.

Here is my code:
`var query = new Query()
    .SetNbHitsPerPage(settings.PageSize)
    .SetPage(settings.PageIndex);

// set query facetfilter

var it = index.BrowseAll(query);
int countFromOffset = it.Count(); // Throws an Exception if query asks the last incomplete page

var result = new BrowseResult
{
    PageIndex = settings.PageIndex,
    PageSize = settings.PageSize,
};
result.TotalCount = result.PageIndex * result.PageSize + countFromOffset;
result.PageCount = result.TotalCount / result.PageSize;
if (result.PageCount * result.PageSize < result.TotalCount)
    result.PageCount++;

result.Items = it.Take(result.PageSize)
    .Select(item => item.ToObject<Product>())
    .ToList();`

The full result of BrowsAll contains 1080 items and each of our pages contains 48 items.
So there are 23 pages to display and the last one should only contains 24 items.

If `query` page is set to 22 (the last page), parsing the iterator throws the AgloliaException : 
`you should pass cursor of current page to fetch next page`

Is it a bug or a wrong usage ?
Thanks for your help

**Comment by CBaptiste** [comment]
I am going to look into it and come back to you !

**Comment by CBaptiste** [comment]
Actually with the BrowseAll method, you should never think about pages and only use the dynamic cursor to manage the "browsing" of your index. The SetPage is probably what is causing the exception, you should not use it in the BrowseAll method
So you will have to change a little bit your implementation to only use the dynamic cursor to fetch the next chunk of data
Is it clear ?

**Comment by ToineSeiter** [comment]
Thanks for you answer but I need pages for our SEO.
I think I will bypass this by merging the last two pages.

**Comment by CBaptiste** [comment]
Hey @ToineSeiter, seems to be a little irrelevant since this issue is 2 months old but did you get to the result you wanted ? 
Don't hesitate to contact me if you have any trouble, I ll be happy to help !

**Comment by ToineSeiter** [comment]
The issue is due to the iterator witch doesn't identified the end of the cursor.
I bypass it by :
- always setting the page index in the query to 0 before calling BrowseAll(). It avoids the exception on "it.Count()" when the page index of the query is set to the last page.
- using it.Skip(offset).Take(computedSizeOfTheCurrentPage)

The idea is to manage the end of the cursor instead of the iterator.
Hope this will help someone... :)

Here is my final Browse method:

        public BrowseResult Browse(BrowseSettings settings = null)
        {
            if (settings == null)
                settings = new BrowseSettings();

            InitSearch();
            Index index = AlgoliaClient.InitIndex(AlgoliaInfo.IndexName);

            var result = new BrowseResult
            {
                PageIndex = settings.PageIndex,
                PageSize = settings.PageSize.GetValueOrDefault(settings.DefaultPageSize),
            };

            // Algolia hack
            settings.PageIndex = 0;

            Query query = CreateQuery(settings);
            var it = index.BrowseAll(query);

            result.TotalCount = it.Count();
            result.PageCount = result.TotalCount / result.PageSize;
            
            if (result.PageCount * result.PageSize < result.TotalCount)
                result.PageCount++;

            if (result.PageIndex >= result.PageCount && result.PageIndex > 0)
                throw new ArgumentOutOfRangeException("page", result.PageIndex, "This page doesn't exists.");

            int offset = result.PageIndex * result.PageSize;

            result.Items = it.Skip(offset)
                .Take(Math.Min(result.PageSize, result.TotalCount - offset))
                .Select(item => item.ToObject<Product>())
                .ToList();

            return result;
        }

**Comment by CBaptiste** [comment]
Ok @ToineSeiter I am glad it worked out :)

I just synched with the team though, and `BrowseAll`using the page index parameter is not really supported anymore. You definitely should use the cursor that the `Browse`method return on the first call and then use a `BrowseFrom` to get the next page. (the first iteration will be the first page, 2nd iteration 2nd page and so on)

It will be for next time. In the meantime I am closing this, come back to me if needed !

Baptiste
