### ISSUE TITLE
[bug]: V7 ISearchClient does not expose PartialUpdateObjectsAsync nor PartialUpdateObjects

### ISSUE THREAD

**Issue by VGonzalez-Edcpub** [algolia/algoliasearch-client-csharp#864]
### Description

The the interface ISearchClient does not expose the  PartialUpdateObjectsAsync and PartialUpdateObjects methods to update multiple objects in one request.

### Client

Search

### Version

7.2,4

**Comment by millotp** [comment]
Thanks for the report, this will be fixed in the next version
