### ISSUE TITLE
Add optionalFacetFilters query parameter

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-client-csharp#89]
Probably something similar to `SetFacetFilters`.

**Comment by kokliKo** [comment]
@CBaptiste up :)

**Comment by CBaptiste** [comment]
yes !! today :)

**Comment by CBaptiste** [comment]
hello @kokliKo @redox ,
After talking to @Nagriar and @clement-leprovost, the feature will not be implemented right now since it has not offically be released

**Comment by Nagriar** [comment]
@CBaptiste Could be cool to implement a low level setter for new parameters in mean time like in objc: 
- https://github.com/algolia/algoliasearch-client-objc/blob/master/src/ASQuery.m#L531-L537
- https://github.com/algolia/algoliasearch-client-objc/blob/master/src/ASQuery.m#L520-L526

**Comment by CBaptiste** [comment]
I have a low level setter: AddCustomParameter(string name, string value) @Nagriar

**Comment by redox** [comment]
👍

**Comment by Nagriar** [comment]
I didn't manage to find it because it doesn't start with `set`, should we add an alias `SetCustomParameter(string name, string value)` ? At the end, we override the value compared to AddInsidePolygon which appends.

**Comment by CBaptiste** [comment]
Yes ok, makes sense !

**Comment by Ant-hem** [comment]
Resolved with version 6.0 - 0fc38a6
