### ISSUE TITLE
Bug in the concatenation of polygon points.

### ISSUE THREAD

**Issue by Nagriar** [algolia/algoliasearch-client-csharp#96]
We miss a coma to split the points: https://github.com/algolia/algoliasearch-client-csharp/blob/master/Algolia.Search/Query.cs#L633

**Comment by CBaptiste** [comment]
hey @Nagriar, you mean a comma between 2 coordinates ? are you sure it is a comma ? it will give insidePolygon="coord1,coord2,coord3,coord4.."

**Comment by Nagriar** [comment]
Yes currently the output is: `insidePolygon="coord1p1,coord1p2coord2p1,coord2p2.."` so we can't parse it.
I rechecked here to be sure :) => https://www.algolia.com/doc/rest-api/search#param-insidePolygon

**Comment by CBaptiste** [comment]
alright ! on it !

**Comment by CBaptiste** [comment]
oh this was released with the previous release !
